### ISSUE TITLE
Haltepunkte von Freizeitbahnen aus der Prozessierung für Fernbahnhöfe rausnehmen

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/atlas-app#140]
Bahnhöfe der Bimmelbahn im Britzergarten werden im Atlas als Fernbahöfe kategorisiert. Diese sollte dort gar nicht auftaichen oder oder in eigener Kategorie: Beispiel: https://radverkehrsatlas.de/regionen/radplus?map=15.3/52.4314/13.4136&config=1tdocms.2hzx8k.3lt&data=radplus-fahrten-2023--route_count,radplus-radparkeninfo-radabstellanlagen&v=2&f=14|node/276690989|13.412204|52.43231

**Comment by Hejco** [comment]
@tordans @rush42 guck mal ob es möglichkeiten gibt diese Bahnhöfe rauszunehmen

**Comment by rush42** [comment]
Ja, ist es. Es gitb den `usage` key, welcher in diesem fall auf `tourism` gesetzt ist. Ich denke das gleich sollte man wahrscheinlich für die [Parkeisenbahn in der Wuhlheide](https://www.openstreetmap.org/node/7590477149#map=13/52.46009/13.54065) auch setzen @tordans .

**Comment by Hejco** [comment]
erscheint mir sinnvoll, du kannst es von mir gerne umsetzen

**Comment by tordans** [comment]
Das ist ein Duplikat von https://github.com/FixMyBerlin/private-issues/issues/1756
Ich schließe hier und wir machen https://github.com/FixMyBerlin/private-issues/issues/1756…
