### ISSUE TITLE
crossings als Kategorie ergänzen

### ISSUE THREAD

**Issue by SupaplexOSM** [FixMyBerlin/atlas-app#23]
In der Datenstruktur könnten crossings noch eine neue Kategorie bilden – immer dann, wenn `highway=foo` + `foo=crossing` ist, also z.B. `cycleway=crossing` / `path=crossing` / `footway=crossing`+`bicycle=[yes|designated]`.

Als Name für die Kategorie bietet sich z.B. "Straßenquerung", "Querung", "Querungsstelle" an – je nach Tagging könnte man sie auch explizit als "Radwegefurt" bezeichnen, aber ich befürchte, das ist schwer zuverlässig aus den Daten zu lesen, ob es wirklich eine markierte Furt ist (würde ggf. erfordern, die Attribute des durchfahrenen crossing-Nodes auszulesen, z.B. wenn `crossing=traffic_signals` oder `crossing:markings` != `no`, denn diese Attribute werden meist nicht an den way geschrieben).

- Beispiel unmarkierter Übergang: [OSM](https://www.openstreetmap.org/way/1015325150) | [Atlas](https://develop--radverkehrsatlas.netlify.app/regionen/trto?lat=52.4757&lng=13.43018&zoom=17.8&theme=bikelanes&bg=cyclosm&config=!(i~fromTo~topics~!(i~shops~a~~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~buildings~a~_F~s~!(i~default~a))(i~landuse~a~~s~!(i~default~a))(i~boundaries~a~_F~s~!(i~default~a~~f~!(i~admin*_level~o~!(i~*7~a~_F)(i~*8~a)))))(i~bikelanes~topics~!(i~bikelanes~a~~s~!(i~default~a)(i~atlas*_bikelanes*_verified~a~_F))(i~bikelanesPresence~a~_F~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))(i~lit~topics~!(i~lit~a~~s~!(i~default~a)(i~atlas*_lit*_complete~a~_F)(i~atlas*_lit*_verified~a~_F)(i~atlas*_lit*_fresh~a~_F))(i~places~a~_F~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))~)
- Beispiel markierter Übergang/Radwegefurt: [OSM](https://www.openstreetmap.org/way/793512030) | [Atlas](https://develop--radverkehrsatlas.netlify.app/regionen/trto?lat=52.48771&lng=13.42591&zoom=18.1&theme=bikelanes&bg=cyclosm&config=!(i~fromTo~topics~!(i~shops~a~~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~buildings~a~_F~s~!(i~default~a))(i~landuse~a~~s~!(i~default~a))(i~boundaries~a~_F~s~!(i~default~a~~f~!(i~admin*_level~o~!(i~*7~a~_F)(i~*8~a)))))(i~bikelanes~topics~!(i~bikelanes~a~~s~!(i~default~a)(i~atlas*_bikelanes*_verified~a~_F))(i~bikelanesPresence~a~_F~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))(i~lit~topics~!(i~lit~a~~s~!(i~default~a)(i~atlas*_lit*_complete~a~_F)(i~atlas*_lit*_verified~a~_F)(i~atlas*_lit*_fresh~a~_F))(i~places~a~_F~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))~)

**Comment by tordans** [comment]
Die neue Kategorie ist heute eingeführt. Kann aber morgen Vormittag getestet werden auf Staging.

Die Unter-Kategorien lasse ich erstmal weg, da die Details nicht so wichtig sind im Moment.
