### ISSUE TITLE
Unter bestimmten Umständen "Einbahnstraße" an Schutzstreifen/Radfahrstreifen – generell unnötig

### ISSUE THREAD

**Issue by SupaplexOSM** [FixMyBerlin/atlas-app#24]
Wenn an einer lane/Schutzstreifen/Radfahrstreifen explizit `cycleway:*:oneway=yes` getaggt ist (was unnötig ist, da es der default ist), erscheint im Atlas auch explizit das Attribut "Fahrtrichtung: Einbahnstraße" (Beispiel Werbellinstraße: [OSM](https://www.openstreetmap.org/way/764644565) | [Atlas](https://develop--radverkehrsatlas.netlify.app/regionen/trto?lat=52.47779&lng=13.42883&zoom=17.1&theme=bikelanes&bg=cyclosm&config=!(i~fromTo~topics~!(i~shops~a~~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~buildings~a~_F~s~!(i~default~a))(i~landuse~a~~s~!(i~default~a))(i~boundaries~a~_F~s~!(i~default~a~~f~!(i~admin*_level~o~!(i~*7~a~_F)(i~*8~a)))))(i~bikelanes~topics~!(i~bikelanes~a~~s~!(i~default~a)(i~atlas*_bikelanes*_verified~a~_F))(i~bikelanesPresence~a~_F~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))(i~lit~topics~!(i~lit~a~~s~!(i~default~a)(i~atlas*_lit*_complete~a~_F)(i~atlas*_lit*_verified~a~_F)(i~atlas*_lit*_fresh~a~_F))(i~places~a~_F~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))~)) – ansonsten (also meistens) aber nicht, denn es wird selten explizit getaggt.

Bei Radfahrstreifen oder Schutzstreifen würde ich nur im sehr seltenen Fall eines Zweirichtungsradwegs einen Hinweis zur Fahrtrichtung erwarten (z.B. korrekt hier, Bergmannstraße: [OSM](https://www.openstreetmap.org/way/962654822) | [Atlas](https://develop--radverkehrsatlas.netlify.app/regionen/trto?lat=52.48903&lng=13.39354&zoom=18.6&theme=bikelanes&bg=cyclosm&config=!(i~fromTo~topics~!(i~shops~a~~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~buildings~a~_F~s~!(i~default~a))(i~landuse~a~~s~!(i~default~a))(i~boundaries~a~_F~s~!(i~default~a~~f~!(i~admin*_level~o~!(i~*7~a~_F)(i~*8~a)))))(i~bikelanes~topics~!(i~bikelanes~a~~s~!(i~default~a)(i~atlas*_bikelanes*_verified~a~_F))(i~bikelanesPresence~a~_F~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))(i~lit~topics~!(i~lit~a~~s~!(i~default~a)(i~atlas*_lit*_complete~a~_F)(i~atlas*_lit*_verified~a~_F)(i~atlas*_lit*_fresh~a~_F))(i~places~a~_F~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))~) | [Mapillary](https://www.mapillary.com/app/?lat=52.4891275&lng=13.3935852&z=17&panos=true&pKey=730927861366585&focus=photo&x=0.5369794885837329&y=0.6764538863149052&zoom=0)).

**Comment by tordans** [comment]
Ich denke, wir sollten aus Atlas-Sicht – also für eine Zielgruppe die OSM und ihre Defaults nicht kennt – überall explizit sein.

Ich würde daher eher sagen, dass wir in der Prozessierung die Defaults explizit machen. Am besten noch so, dass wir nachvollziehen können, woher der Wert kommt.

Sprich hier…

Wenn `cycleway:SIDE=track|lane` und `cycleway:SIDE:oneway=NULL`, 
  dann setzen wir explizit `oneway=yes+oneway_source=default_value` 
  oder `oneway=yes_default_value`

---

Welche values würde das noch betreffen?

**Comment by tordans** [comment]
Next steps: Wir machen jetzt im Rahmen von https://github.com/FixMyBerlin/private-issues/issues/540 erstmal die `oneway=yes_default_value` Lösung.

**Comment by rush42** [comment]
ist gepusht auf develop mit `yes (implicit)`
