### ISSUE TITLE
Atlas: (Klären in #28) Führungsformen "Einrichtungsradweg" und "Zweirichtungsradweg" klar benennen

### ISSUE THREAD

**Issue by SupaplexOSM** [FixMyBerlin/atlas-app#25]
In der Radverkehrsplanung werden "tracks" im OSM-Sinne, also straßenbegleitende, baulich getrennte Radwege, als _Einrichtungsradweg_ bzw. ggf. als _Zweirichtungsradweg_ bezeichnet (siehe z. B. [1](http://www.mobilitaetsforum.de/dokumente/2018-03-17/Unterlagen/12_ADFC_Teltow_Fuehrungsformen_2018-03-12.pdf) | [2](https://www.darmstadtfaehrtrad.org/wp/wp-content/uploads/2017/08/Radwegbreiten-1.pdf) | [3](https://backend.orlis.difu.de/server/api/core/bitstreams/64877a4d-14e6-4f04-9f6a-30db4b64e5c1/content), S. 11). Diese Begriffe sollten daher direkt bei der Führungsform auftauchen (statt "Radweg, baulich von der Fahrbahn abgesetzt").

Also wenn `track` oder `cycleway` + `is_sidepath`, und `oneway != no`, dann "Einrichtungsradweg". Sonst, wenn `oneway=no`, dann "Zweirichtungsradweg".

Zur Zeit gibt es die Kategorie "Zwei-Richtungsstraße/-radweg" – lässt sich das nicht gut präzisieren? Also wenn es ein Radweg ist, von "Zweirichtungsradweg" sprechen – bei einer Straße (z.B. Fahrradstraße?) ist es ja eigentlich der default, dass sie "Zweirichtungsstraße" ist.

- Beispiel "Zweirichtungsradweg" (separat gemappt): [OSM](https://www.openstreetmap.org/way/949514221) | [Atlas](https://develop--radverkehrsatlas.netlify.app/regionen/trto?lat=52.44255&lng=13.45726&zoom=17.2&theme=bikelanes&bg=cyclosm&config=!(i~fromTo~topics~!(i~shops~a~~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~buildings~a~_F~s~!(i~default~a))(i~landuse~a~~s~!(i~default~a))(i~boundaries~a~_F~s~!(i~default~a~~f~!(i~admin*_level~o~!(i~*7~a~_F)(i~*8~a)))))(i~bikelanes~topics~!(i~bikelanes~a~~s~!(i~default~a)(i~atlas*_bikelanes*_verified~a~_F))(i~bikelanesPresence~a~_F~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))(i~lit~topics~!(i~lit~a~~s~!(i~default~a)(i~atlas*_lit*_complete~a~_F)(i~atlas*_lit*_verified~a~_F)(i~atlas*_lit*_fresh~a~_F))(i~places~a~_F~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))~)
- Beispiel "Einrichtungsradweg" (separat gemappt): [OSM](https://www.openstreetmap.org/way/762925072) | [Atlas](https://develop--radverkehrsatlas.netlify.app/regionen/trto?lat=52.4729&lng=13.4385&zoom=16.5&theme=bikelanes&bg=cyclosm&config=!(i~fromTo~topics~!(i~shops~a~~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~buildings~a~_F~s~!(i~default~a))(i~landuse~a~~s~!(i~default~a))(i~boundaries~a~_F~s~!(i~default~a~~f~!(i~admin*_level~o~!(i~*7~a~_F)(i~*8~a)))))(i~bikelanes~topics~!(i~bikelanes~a~~s~!(i~default~a)(i~atlas*_bikelanes*_verified~a~_F))(i~bikelanesPresence~a~_F~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))(i~lit~topics~!(i~lit~a~~s~!(i~default~a)(i~atlas*_lit*_complete~a~_F)(i~atlas*_lit*_verified~a~_F)(i~atlas*_lit*_fresh~a~_F))(i~places~a~_F~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))~)

**Comment by tordans** [comment]
Dieses Thema haben wir inzwischen behoben, ich schließe das Ticket daher.

Aktuelle Test Links:
- [Einrichtungsradweg](https://radverkehrsatlas.de/regionen/berlin?bg=default&map=16.5/52.4729/13.4385&v=1&config=!(i~poi~a~_F~sc~!(i~poi~s~!(i~hidden~a~_F)(i~default~a)(i~education~a~_F))(i~poiPlaces~s~!(i~hidden~a~_F)(i~default~a)(i~circle~a~_F))(i~poiBoundaries~s~!(i~hidden~a)(i~default~a~_F)(i~category*_district*_label~a~_F)(i~category*_municipality~a~_F)(i~category*_municipality*_label~a~_F))(i~poiPlusBarriers~s~!(i~default~a~_F))(i~poiPlusLanduse~s~!(i~default~a~_F))(i~poiPlusPublicTransport~s~!(i~default~a~_F)))(i~bikelanes~a~~sc~!(i~bikelanes~s~!(i~hidden~a~_F)(i~default~a)(i~details~a~_F)(i~width~a~_F))(i~bikelanes*_plus*_presence~s~!(i~default~a~_F))(i~bikelanes*_plus*_width~s~!(i~default~a~_F))(i~bikelanes*_plus*_surface*_smoothness~s~!(i~default~a~_F))(i~bikelanes*_plus*_signs~s~!(i~default~a~_F))(i~bikelanes*_plus*_routes~s~!(i~default~a~_F)))(i~roads~a~_F~sc~!(i~roads~s~!(i~hidden~a~_F)(i~default~a)(i~sidestreets~a~_F)(i~mainstreets~a~_F))(i~maxspeed~s~!(i~hidden~a)(i~default~a~_F)(i~below30~a~_F)(i~above40~a~_F))(i~roads*_plus*_footways~s~!(i~default~a~_F)))(i~surface~a~_F~sc~!(i~surfaceRoads~s~!(i~hidden~a~_F)(i~default~a)(i~bad~a~_F))(i~surfaceBikelanes~s~!(i~hidden~a)(i~default~a~_F)(i~bad~a~_F)))(i~parking~a~_F~sc~!(i~parking~s~!(i~hidden~a~_F)(i~default~a)(i~presence~a~_F)(i~surface~a~_F))(i~parkingPoints~s~!(i~hidden~a)(i~default~a~_F))(i~parkingAreas~s~!(i~hidden~a~_F)(i~default~a)(i~street*_side~a~_F))(i~parkingDebug~s~!(i~hidden~a)(i~default~a~_F))(i~parkingStats~s~!(i~hidden~a)(i~stats-admin-level-4~a~_F)(i~default~a~_F)(i~stats-admin-level-10~a~_F)(i~length-admin-level-4~a~_F)(i~length-admin-level-9~a~_F)(i~length-admin-level-10~a~_F))(i~signs~s~!(i~hidden~a)(i~default~a~_F)))(i~bicycleParking~a~_F~sc~!(i~bicycleParking~s~!(i~hidden~a~_F)(i~default~a)))(i~mapillary~a~_F~sc~!(i~mapillaryCoverage~s~!(i~hidden~a~_F)(i~default~a)(i~all~a~_F)(i~age~a~_F)(i~pano~a~_F)))~)
- [Zweirichtungsradwege](https://radverkehrsatlas.de/regionen/deutschland?bg=default&map=19/52.44274/13.45657&v=1&config=!(i~bikelanes~a~~sc~!(i~bikelanes~s~!(i~hidden~a~_F)(i~default~a)(i~details~a~_F)(i~width~a~_F))(i~bikelanes*_plus*_presence~s~!(i~default~a~_F))(i~bikelanes*_plus*_width~s~!(i~default~a~_F))(i~bikelanes*_plus*_surface*_smoothness~s~!(i~default~a~_F))(i~bikelanes*_plus*_signs~s~!(i~default~a~_F))(i~bikelanes*_plus*_routes~s~!(i~default~a~_F)))(i~poi~a~_F~sc~!(i~poi~s~!(i~hidden~a~_F)(i~default~a)(i~education~a~_F))(i~poiPlaces~s~!(i~hidden~a~_F)(i~default~a)(i~circle~a~_F))(i~poiBoundaries~s~!(i~hidden~a)(i~default~a~_F)(i~category*_district*_label~a~_F)(i~category*_municipality~a~_F)(i~category*_municipality*_label~a~_F))(i~poiPlusBarriers~s~!(i~default~a~_F))(i~poiPlusLanduse~s~!(i~default~a~_F))(i~poiPlusPublicTransport~s~!(i~default~a~_F)))(i~roads~a~_F~sc~!(i~roads~s~!(i~hidden~a~_F)(i~default~a)(i~sidestreets~a~_F)(i~mainstreets~a~_F))(i~maxspeed~s~!(i~hidden~a)(i~default~a~_F)(i~below30~a~_F)(i~above40~a~_F))(i~roads*_plus*_footways~s~!(i~default~a~_F)))(i~surface~a~_F~sc~!(i~surfaceRoads~s~!(i~hidden~a~_F)(i~default~a)(i~bad~a~_F))(i~surfaceBikelanes~s~!(i~hidden~a)(i~default~a~_F)(i~bad~a~_F)))(i~lit~a~_F~sc~!(i~lit~s~!(i~hidden~a~_F)(i~default~a)(i~lit~a~_F))(i~lit-completeness~s~!(i~completeness~a~_F)))(i~mapillary~a~_F~sc~!(i~mapillaryCoverage~s~!(i~hidden~a~_F)(i~default~a)(i~all~a~_F)(i~age~a~_F)(i~pano~a~_F)))~&f=10|way/949514221|13.456321|52.442539|13.456686|52.442866)
