### ISSUE TITLE
Übersetzung `footAndCycleway_segregated_adjoining`

### ISSUE THREAD

**Issue by SupaplexOSM** [FixMyBerlin/atlas-app#26]
Fehlt noch eine [Übersetzung](https://github.com/FixMyBerlin/atlas-app/edit/develop/src/components/MapInterface/Inspector/TagsTable/translations/translations.const.ts) für `tarmac_bikelanes--category=footAndCycleway_segregated_adjoining` (z.B. "Getrennter Geh- und Radweg / Rad- und Gehweg, straßenbegleitend") oder wird daran gerade gearbeitet? (Beispiel [OSM](https://www.openstreetmap.org/way/824612665) | [Atlas](https://develop--radverkehrsatlas.netlify.app/regionen/trto?lat=52.4536&lng=13.4447&zoom=16.6&theme=bikelanes&bg=cyclosm&config=!(i~fromTo~topics~!(i~shops~a~~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~buildings~a~_F~s~!(i~default~a))(i~landuse~a~~s~!(i~default~a))(i~boundaries~a~_F~s~!(i~default~a~~f~!(i~admin*_level~o~!(i~*7~a~_F)(i~*8~a)))))(i~bikelanes~topics~!(i~bikelanes~a~~s~!(i~default~a)(i~atlas*_bikelanes*_verified~a~_F))(i~bikelanesPresence~a~_F~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))(i~lit~topics~!(i~lit~a~~s~!(i~default~a)(i~atlas*_lit*_complete~a~_F)(i~atlas*_lit*_verified~a~_F)(i~atlas*_lit*_fresh~a~_F))(i~places~a~_F~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))~))

Könnte auch `footAndCycleway_segregated_isolated` betreffen sowie die jeweiligen `tarmac_bikelanesPresence--LEFTRIGHTSELF`-Versionen.

**Comment by tordans** [comment]
Ich habe die Übersetzungen neu im Rahmen der neuen Kategorisierung korrigiert. Details wie https://github.com/FixMyBerlin/atlas-app/issues/25 ist noch offen, aber dieser konkrete Fall ist behoben.

(Testing möglich ab morgen, wenn Staging wieder ganz funktioniert.)
