### ISSUE TITLE
Übersetzung für "Verkehrszeichen: none"

### ISSUE THREAD

**Issue by SupaplexOSM** [FixMyBerlin/atlas-app#27]
Für "Verkehrszeichen: none" sollte eine Übersetzung angeboten werden ("Verkehrszeichen: Unbeschildert"?)

Beispiel: [OSM](https://www.openstreetmap.org/way/824612665) | [Atlas](https://develop--radverkehrsatlas.netlify.app/regionen/trto?lat=52.4536&lng=13.4447&zoom=16.6&theme=bikelanes&bg=cyclosm&config=!(i~fromTo~topics~!(i~shops~a~~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~buildings~a~_F~s~!(i~default~a))(i~landuse~a~~s~!(i~default~a))(i~boundaries~a~_F~s~!(i~default~a~~f~!(i~admin*_level~o~!(i~*7~a~_F)(i~*8~a)))))(i~bikelanes~topics~!(i~bikelanes~a~~s~!(i~default~a)(i~atlas*_bikelanes*_verified~a~_F))(i~bikelanesPresence~a~_F~s~!(i~default~a))(i~places~a~~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))(i~lit~topics~!(i~lit~a~~s~!(i~default~a)(i~atlas*_lit*_complete~a~_F)(i~atlas*_lit*_verified~a~_F)(i~atlas*_lit*_fresh~a~_F))(i~places~a~_F~s~!(i~default~a)(i~atlas*_placescircle~a~_F))(i~landuse~a~_F~s~!(i~default~a)))~)

**Comment by tordans** [comment]
Ist umgesetzt auf Staging.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/111561/228208650-5e7480bf-3420-413f-99ee-80a17be6ef08.png">
