### ISSUE TITLE
Atlas: Bing-Luftbilder als Hintergrund ergänzen

### ISSUE THREAD

**Issue by SupaplexOSM** [FixMyBerlin/atlas-app#36]
Gab es schon den Versuch, Bing-Luftbilder als möglichen Hintergrund zu ergänzen oder macht die Bing-API das schwer?

- Wenn ich richtig sehe, gibt es [auf der MS-Website](https://learn.microsoft.com/en-us/bingmaps/rest-services/imagery/get-a-static-map) Infos zum einbinden
- In QGIS binde ich sie mit der URL `http://ecn.t3.tiles.virtualearth.net/tiles/a{q}.jpeg?g=1` ein.

**Comment by tordans** [comment]
Für die Bing-Luftbilder bräuchten wir einen API Key und müssten für den Traffic zahlen. (Die OSM Community bekommst einen kostenlosen API Key pro Tool.)

Bisher haben wir noch keine Erfahrung mit API Keys und Kosten in der Bing-Welt. 

Aktuell haben wir nur diese ERSI Luftbilder im System, die auch im OSM Ökosystem eine Freigabe haben.

Ich schlage diese Ergänzungen vor:

- [ ] Mapbox Satellite Layer einfügen
- [ ] Maptiler Satellite Layer einfügen

Für diese beiden Layer haben wir bereits ein Setup.

**Comment by SupaplexOSM** [comment]
Auch gut. Bing zeichnet sich inzwischen in einigen Regionen durch extrem gute und hochaufgelöste Bilder aus, aber wenn es da Lizensierungshürden gibt, dann ist das eben so. Hier ein [Vergleich für BiBi, (1) Bing, (2) Mapbox, (3) ESRI](https://mc.bbbike.org/mc/?lon=9.133466&lat=48.952784&zoom=17&num=3&mt0=bing-satellite&mt1=mapbox-satellite&mt2=esri-satellite) – man kann bei Bing leider nicht weiter reinzoomen, vielleicht auch wegen der API-/Lizenz-Hürden.

**Comment by tordans** [comment]
Es gibt jetzt diese drei:

- Esri https://develop--radverkehrsatlas.netlify.app/regionen/parkraum?lat=52.4918&lng=13.4261&zoom=13.5&theme=parking&bg=esri
- Maptiler https://develop--radverkehrsatlas.netlify.app/regionen/parkraum?lat=52.4918&lng=13.4261&zoom=13.5&theme=parking&bg=maptiler-satellite
- Maptiler https://develop--radverkehrsatlas.netlify.app/regionen/parkraum?lat=52.4918&lng=13.4261&zoom=13.5&theme=parking&bg=mapbox-satellite

Kommt bald in Production.

@hekele zur Abnahme an dich.

**Comment by hekele** [comment]
@Hejco magst Du das abnehmen? Ist schon länger offen. Ich kann da gar nicht so viel zu sagen :-)
